id: P000418
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:38:56.164039
source_metadata:
  id: bdr:W1KG22377
  title: རྩ་རྒྱུད་རྟོག་བདུན་སོགས།
  author: ''
  volumes:
    cb4fbb0536fc4c28aa22d49670803418:
      image_group_id: I1KG22396
      title: Volume 1 of rdo rje 'jigs byed kyi rtsa ba'i rgyud rtog pa bdun pa sogs/
      volume_number: 1
      total_pages: 1030
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
